twig:
    default_path: '%kernel.project_dir%/templates'
    # ...

    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/public/picture': images
when@test:
    twig:
        strict_variables: true
